name: car_lookup_pam
description: "Projekt zaliczeniowy na przedmiot Programowanie Aplikacji Mobilnych"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  http: ^1.2.0
  sqflite: ^2.2.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
